App_Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from App_Blog import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('Blog.urls')),
    path('', views.Index, name="index"),

    

 # Password reset
    path("password-reset/",auth_views.PasswordResetView.as_view(), name="password_reset"),
    path("password-reset/done/",auth_views.PasswordResetDoneView.as_view(),
         name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/",auth_views.PasswordResetConfirmView.as_view(),
         name="password_reset_confirm"),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

App_Login/urls.py
from django.urls import path
from App_Login import views
app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name="signup"),
    path('login/', views.login_page, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('change-profile/', views.change_user, name='user_change'),
    path('password/', views.pass_change, name="pass_change"),
    path('add-picture/', views.add_pro_pic, name="add_pro_pic"),
     path('change-picture/', views.change_pro_pic, name="change_pro_pic")

]

Blog/urls.py
from django.urls import path
from Blog import views
app_name = 'Blog'
urlpatterns = [
    path('', views.blog_list, name="blog_list"),
    # path('',  views.BlogList.as_view(), name="blog_list"),
    path('write/', views.CreateBlog.as_view(), name="create_blog"),
    path('details/<str:slug>/', views.blog_details, name="blog_details"),
    path('liked/<pk>/', views.liked, name="liked_post"),
    path('unliked/<pk>/', views.unliked, name="unliked_post"),
    # path('user-blogs/', views.MyBlogs.as_view(), name="user_blog"),
    path('my-blogs/', views.my_blogs, name='user_blog'),
    path('edit-blog/<pk>/', views.EditBlog.as_view(), name="edit_blog"),
    path('delete-blog/<pk>/', views.DeleteBlog.as_view(), name="delete_blog"),
    path('delete-success/', views.DeleteSuccess.as_view(), name="delete_success"),
    path('create-category/', views.CreateCategory.as_view(), name='create_category'),
    path('all-categories/', views.ShowCategory.as_view(), name='all_categories'),
    path('show-all-categories/<pk>', views.show_all_categories, name='show_all_categories'),
    path('update-category/<pk>', views.EditCategory.as_view(), name='update_category'),
    path('user-categories/', views.MyCategories.as_view(), name='user_categories'),
    path('delete-category/<pk>', views.DeleteCategory.as_view(), name='delete_category'),
    path('query/', views.ask_ai, name="query"),
    path('user-location/', views.know_location, name='user_location')
    
    # path('category/<str:category>/', views.category_view, name='blog_category'),
    # path('all-categories/', views.AllCategories.as_view(), name="all_categories"),
    # path('category_view/<int:category>', views.category_view, name="category_view")

]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title_block %}Awesome Blog Site{% endblock  %}</title>
    {% comment %} BOOTSTRAP (CSS) {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    {% comment %} FONT AWESOME (CSS) {% endcomment %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% comment %} BOOTSTRAP (JS) {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous" defer></script>
    <link rel="stylesheet" href="{% static 'css/style.css'%}">

    <style>

        {% block css_block %}{% endblock %}
    </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-danger">
    <div class="container">
      <a class="nav-link active" aria-current="page" href="{% url 'index' %}"><i class="fa-solid fa-blog fa-2xl" style="color:#FFFFFF"></i></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto text-center">
        
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'Blog:user_location' %}">Your Location</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'Blog:all_categories' %}">Cities</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'Blog:query' %}">Ask Travel Guide</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              @{{user.username}}
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'Blog:create_category' %}">Create Category</a></li>
              <li><a class="dropdown-item" href="{% url 'Blog:create_blog' %}">Write blog</a></li>
              <li><a class="dropdown-item" href="{% url 'Blog:user_categories' %}">My categories</a></li>
              <li><a class="dropdown-item" href="{% url 'Blog:user_blog' %}">My Blogs</a></li>
              <li><a class="dropdown-item" href="{% url 'App_Login:profile' %}">Profile</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a></li>
            </ul>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link text-light " href="{% url 'App_Login:signup' %}">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light " href="{% url 'App_Login:login' %}">Log In</a>
          </li>
          {% endif %}
         
         
        </ul>
      </div>
    </div>
  </nav>

      <div class="container pt-5">
        {% if not user.is_authenticated %}
        <h6 class="text-center fw-bold fs-6">Sign in to read full posts</h6>
        {% endif %}
        {% block body_block %}
        
        {% endblock  %}
      </div>
    
    
</body>
</html>