App_Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from App_Blog import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('Blog.urls')),
    path('', views.Index, name="index"),

    

 # Password reset
    path("password-reset/",auth_views.PasswordResetView.as_view(), name="password_reset"),
    path("password-reset/done/",auth_views.PasswordResetDoneView.as_view(),
         name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/",auth_views.PasswordResetConfirmView.as_view(),
         name="password_reset_confirm"),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Blog/urls.py
from django.urls import path
from Blog import views
app_name = 'Blog'
urlpatterns = [
    path('', views.blog_list, name="blog_list"),
    # path('',  views.BlogList.as_view(), name="blog_list"),
    path('write/', views.CreateBlog.as_view(), name="create_blog"),
    path('details/<str:slug>/', views.blog_details, name="blog_details"),
    path('liked/<pk>/', views.liked, name="liked_post"),
    path('unliked/<pk>/', views.unliked, name="unliked_post"),
    # path('user-blogs/', views.MyBlogs.as_view(), name="user_blog"),
    path('my-blogs/', views.my_blogs, name='user_blog'),
    path('edit-blog/<pk>/', views.EditBlog.as_view(), name="edit_blog"),
    path('delete-blog/<pk>/', views.DeleteBlog.as_view(), name="delete_blog"),
    path('delete-success/', views.DeleteSuccess.as_view(), name="delete_success"),
    path('create-category/', views.CreateCategory.as_view(), name='create_category'),
    path('all-categories/', views.ShowCategory.as_view(), name='all_categories'),
    path('show-all-categories/<pk>', views.show_all_categories, name='show_all_categories'),
    path('update-category/<pk>', views.EditCategory.as_view(), name='update_category'),
    path('user-categories/', views.MyCategories.as_view(), name='user_categories'),
    path('delete-category/<pk>', views.DeleteCategory.as_view(), name='delete_category'),
    path('query/', views.ask_ai, name="query"),
    path('user-location/', views.know_location, name='user_location')
    
    # path('category/<str:category>/', views.category_view, name='blog_category'),
    # path('all-categories/', views.AllCategories.as_view(), name="all_categories"),
    # path('category_view/<int:category>', views.category_view, name="category_view")

]

App_Blog/views.py
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import HttpResponseRedirect

def Index(request):
    return HttpResponseRedirect(reverse('Blog:blog_list'))

templates/App_Blog/blog_details.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title_block %}{{blog.blog_title}}{% endblock  %}

{% block body_block %}
<div class="container">
    <p class="fw-bold text-center fs-6">Member only story</p>
    <h2 class="text-center ">{{ blog.blog_title }}</h2>
    <h5 class="text-center">City: {{blog.blog_category}}</h5>
    <h6 class="text-center ">By @{{blog.author}}</h6>
    <p class="fs-6 text-center ">Published on: {{blog.publish_date}}</p>
    <hr>
        <div class="text-center">
            {% if not liked %}
            <a href="{%url 'Blog:liked_post' pk=blog.pk %}"><i class="fa-regular fa-thumbs-up"></i></a>  {{ blog.liked_blog.count }} likes
            {% else %}
            <a href="{%url 'Blog:unliked_post' pk=blog.pk %}"><i class="fa-regular fa-thumbs-down"></i></a> {{ blog.liked_blog.count }} likes
            {% endif %}
           | <a><i class="fa-regular fa-comment"></i></a> {{ blog.blog_comment.count }} Comments
        </div>
    <hr>
    <div class="my-3">
        <img src="/media/{{ blog.blog_image }}" alt={{ blog.blog_title }} class="img-fluid mx-auto d-block" width="400">

        <h5>Best meal</h5>
        <p>Meal name: {{ meal_name }} </p>
        <small>Recipe: {{meal_recipe}}</small>
        <hr>

        <div class="">
            <p class="text-justify">{{blog.blog_content|linebreaks}}</p>
        </div>
    </div>
</div>

 <div class="row">
    <div class="col-sm-6">
        <h6>Comments: </h6>
        {% for comment in blog.blog_comment.all %}
        <p><a href="#"> @{{comment.user}} </a> <br> {{ comment }} <br> <small>{{ comment.comment_date }}</small> </p>
        {% endfor %}
    </div>
    <div class="col-sm-6">
        <form method="POST">
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-info btn-sm text-light">Post comment</button>
        </form>
        <br>
    </div>
 </div>


{% endblock  %}

templates/App_Blog/blog_list.html
{% extends "base.html" %}
{% block title_block %} Home {% endblock  %}
{% load custom_filters %}
{% block body_block %}

<div class="container">
  <div class="justify-content-center align-items-center">
    {% comment %} {% if user.is_authenticated %} {% endcomment %}
    <div class="row row-cols-1 row-cols-md-3 g-4 my-3">
      {% for blog in blogs %}
      <div class="col">
        <div class="card h-100">
          <img src="/media/{{ blog.blog_image }}" class="card-img-top img-fluid mx-auto d-block" alt="{{ blog.blot_title}}" width='250px'>
          <div class="card-body">
            <h5 class="card-title">{{ blog.blog_title }}</h5>
            <p class="card-text"> {{ blog.blog_content|range_filter|truncatewords:30 }} </p>
            <a href="{% url 'Blog:blog_details' slug=blog.slug %}" class="btn btn-primary btn-sm">Read more</a>
          </div>
          <div class="card-footer">
            <small class="text-body-secondary">Last updated: {{ blog.update_date }}</small>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <nav aria-label="Page navigation example ">
      <ul class="pagination justify-content-center">
      
      <!-- Previous Page -->
      {% if blogs.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ blogs.previous_page_number }}">Previous</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link">Previous</a>
        </li>
      {% endif %}
  
      <!-- Page Numbers -->
      {% for blog_page in blogs.paginator.page_range %}
          {% if blogs.number == blog_page %}
              <!-- Current page, make it active and disable the link -->
              <li class="page-item active"><a class="page-link" href="?page={{ blog_page }}">{{ blog_page }}</a></li>
          {% else %}
              <!-- Other pages -->
              <li class="page-item"><a class="page-link" href="?page={{ blog_page }}">{{ blog_page }}</a></li>
          {% endif %}
      {% endfor %}
  
      <!-- Next Page -->
      {% if blogs.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ blogs.next_page_number }}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link">Next</a>
        </li>
      {% endif %}
      
      </ul>
  </nav>
    {% comment %} {% endif %} {% endcomment %}
   
  </div>
</div>

{% endblock  %}

templates/App_Blog/category_list.html
{% extends "base.html" %}
{% block title_block %} All Cities {% endblock  %}

{% block body_block %}
   
    <div class="row row-cols-1 row-cols-md-3 g-4 my-3">
        {% for category in categories %}
        <div class="col">
          <div class="card h-100">
            <img src="/media/{{ category.category_image }}" class="card-img-top img-fluid mx-auto d-block" alt="{{ category.category_image}}" width='100px'>
            <div class="card-body">
              <h5 class="card-title text-center">{{ category.category_name }}</h5>
              <a href="{% url 'Blog:show_all_categories' pk=category.pk %}" class="btn btn-primary btn-sm">View all</a>
            </div>
           
          </div>
        </div>
        {% endfor %}
      </div>
    
{% endblock  %}

templates/App_Blog/category_sorted.html
{% extends "base.html" %}
{% block title_block %} Home {% endblock  %}
{% load custom_filters %}
{% block body_block %}
{% if blogs %}
<div class="container">
  <div class="justify-content-center align-items-center">
    {% if user.is_authenticated %}
    <div class="row row-cols-1 row-cols-md-3 g-4 my-3">
      {% for blog in blogs %}
      <div class="col">
        <div class="card h-100">
          <img src="/media/{{ blog.blog_image }}" class="card-img-top img-fluid mx-auto d-block" alt="{{ blog.blot_title}}" width='250px'>
          <div class="card-body">
            <h5 class="card-title">{{ blog.blog_title }}</h5>
            <p class="card-text"> {{ blog.blog_content|range_filter|truncatewords:30 }} </p>
            <a href="{% url 'Blog:blog_details' slug=blog.slug %}" class="btn btn-primary btn-sm">Read more</a>
          </div>
          <div class="card-footer">
            <small class="text-body-secondary">Last updated: {{ blog.update_date }}</small>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <nav aria-label="Page navigation example ">
      <ul class="pagination justify-content-center">
      
      <!-- Previous Page -->
      {% if blogs.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ blogs.previous_page_number }}">Previous</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link">Previous</a>
        </li>
      {% endif %}
  
      <!-- Page Numbers -->
      {% for blog_page in blogs.paginator.page_range %}
          {% if blogs.number == blog_page %}
              <!-- Current page, make it active and disable the link -->
              <li class="page-item active"><a class="page-link" href="?page={{ blog_page }}">{{ blog_page }}</a></li>
          {% else %}
              <!-- Other pages -->
              <li class="page-item"><a class="page-link" href="?page={{ blog_page }}">{{ blog_page }}</a></li>
          {% endif %}
      {% endfor %}
  
      <!-- Next Page -->
      {% if blogs.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ blogs.next_page_number }}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link">Next</a>
        </li>
      {% endif %}
      
      </ul>
  </nav>
    {% endif %}
   
  </div>
</div>
{% else %}
<p>No Post in this category yet.</p>
<a href="{% url 'Blog:create_blog' %}" class="btn btn-primary btn-sm">Add Post</a>
{% endif %}


{% endblock  %}

templates/App_Blog/create_blog.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title_block %} Add Post {% endblock  %}

{% block body_block %}
<h2>Write your blog here: </h2>
<form method="POST" enctype='multipart/form-data'>
    {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Publish</button>
</form>
{% endblock  %}

templates/App_Blog/create_category.html
{% extends "base.html" %}
{% block title_block %} New Category {% endblock  %}
{% load crispy_forms_tags %}
{% block body_block %}
    <form method="POST" enctype="multipart/form-data">
        {{form|crispy}}
        {%csrf_token%}
        <button type="submit" class="btn btn-info btn-sm">Add new category</button>
    </form>
{% endblock  %}

templates/App_Blog/delete_blog.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title_block %} Delete!!! {% endblock  %}

{% block body_block %}
    <h4>Are you sure you want to delete?</h4>
    <form method="POST">
        {{form | crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
    </form>
{% endblock  %}

templates/App_Blog/delete_success.html
{% extends "base.html" %}
{% block title_block %}
Delete success
{% endblock  %}

{% block body_block %}
    <div class="alert alert-danger">
        Deleted!!!
    </div>
{% endblock  %}

templates/App_Blog/edit_blog.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title_block %} {{ user }} {% endblock  %}

{% block body_block %}
    {% if blog.author == user %}
        <h3>Update Post: </h3>
        <form method="POST" enctype='multipart/form-data'>
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-warning btn-sm">Update Post</button>
        </form>
    {% endif %}
{% endblock  %}

templates/App_Blog/maps.html
{% extends "base.html" %}

{% block title_block %} User Location {% endblock  %}

{% block body_block %}
{% if url %}
{{ url }}
{% else %}
<small><a href="{% url 'Blog:all_categories' %}" class="">View Cities</a></small>
{% endif %}
{% endblock  %}

templates/App_Blog/my_blogs.html
{% extends "base.html" %}
{% load custom_filters %}
{% block title_block %} {{ user }} {% endblock  %}

{% block body_block %}
    {% comment %} {% for blog in user.post_author.all %}

        <div class="row">
            <div class="col-sm-4">
                <h6>{{ blog.blog_title }}</h6>
                <img src="/media/{{blog.blog_image}}" class="img-fluid d-block" width="100" alt="">
            </div>
            <div class="col-sm-8">
                <p>{{ blog.blog_content|linebreaks|range_filter|safe }}</p>
                <a href="{% url 'Blog:blog_details' slug=blog.slug %}">Read more</a>
                <br>
                <br>
                <div class="d-flex">
                    <a href="{% url 'Blog:edit_blog' pk=blog.pk %}" class="btn btn-warning btn-sm ">Edit Blog</a>
                    <a  href="{% url 'Blog:delete_blog' pk=blog.pk %}" class="btn btn-danger btn-sm ms-2" >Delete Blog</a>
                </div>
            </div>
        </div>
    {% endfor %} {% endcomment %}
    <div class="container">
        <div class="justify-content-center align-items-center">
          {% comment %} {% if user.is_authenticated %} {% endcomment %}
          <div class="row row-cols-1 row-cols-md-3 g-4 my-3">
            {% for blog in blogs %}
            <div class="col">
              <div class="card h-100">
                <img src="/media/{{ blog.blog_image }}" class="card-img-top img-fluid mx-auto d-block" alt="{{ blog.blot_title}}" width='250px'>
                <div class="card-body">
                  <h5 class="card-title">{{ blog.blog_title }}</h5>
                  <div class="d-flex">
                    <a href="{% url 'Blog:edit_blog' pk=blog.pk %}" class="btn btn-warning btn-sm">Edit</a>
                    <a href="{% url 'Blog:delete_blog' pk=blog.pk %}" class="btn btn-danger btn-sm ms-2">Delete</a>
                  </div>
                  <p class="card-text"> {{ blog.blog_content|range_filter|truncatewords:30 }} </p>
                  <a href="{% url 'Blog:blog_details' slug=blog.slug %}" class="btn btn-primary btn-sm">Read more</a>
                </div>
                <div class="card-footer">
                  <small class="text-body-secondary">Last updated: {{ blog.update_date }}</small>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
          <nav aria-label="Page navigation example ">
            <ul class="pagination justify-content-center">
            
            <!-- Previous Page -->
            {% if blogs.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{ blogs.previous_page_number }}">Previous</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link">Previous</a>
              </li>
            {% endif %}
        
            <!-- Page Numbers -->
            {% for blog_page in blogs.paginator.page_range %}
                {% if blogs.number == blog_page %}
                    <!-- Current page, make it active and disable the link -->
                    <li class="page-item active"><a class="page-link" href="?page={{ blog_page }}">{{ blog_page }}</a></li>
                {% else %}
                    <!-- Other pages -->
                    <li class="page-item"><a class="page-link" href="?page={{ blog_page }}">{{ blog_page }}</a></li>
                {% endif %}
            {% endfor %}
        
            <!-- Next Page -->
            {% if blogs.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ blogs.next_page_number }}">Next</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link">Next</a>
              </li>
            {% endif %}
            
            </ul>
        </nav>
          {% comment %} {% endif %} {% endcomment %}
         
        </div>
      </div>
{% endblock  %}

templates/App_Blog/query.html
{% extends "base.html" %}
{% block title_block %}
    Ask AI
{% endblock  %}
{% load crispy_forms_tags %}
{% load static %}

{% block css_block %}

   .query-form {
    {% comment %} width: 550px; {% endcomment %}
    padding: 30px;
   }
{% endblock  %}
{% block body_block %}
        <img src="/media/guide.avif" class="img-fluid mx-auto d-block" alt="">
        <div class="query-form mx-auto">
            <center class="">
                <form method="POST">
                    {{ form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-sm" style="width:100%">Ask Question</button>
                </form>
            </center>

        </div>

        {% if answer is None %}
        <p></p>
        {% else %}
        <p class="text-center">{{ answer }}</p>
        {% endif %}
   

{% endblock  %}

templates/App_Blog/user_categories.html
{% extends "base.html" %}
{% block title_block %} Home {% endblock  %}
{% load custom_filters %}
{% block body_block %}

<div class="container">
  <div class="justify-content-center align-items-center">
    {% if user.is_authenticated %}
    <div class="row row-cols-1 row-cols-md-3 g-4 my-3">
      {% for category in user.user_category.all %}
      <div class="col">
        <div class="card h-100">
          <img src="/media/{{ category.category_image }}" class="card-img-top img-fluid mx-auto d-block" alt="{{ category.category_name }}" width='250px'>
          <div class="card-body">
            <h5 class="card-title">{{ category.category_name }}</h5>
            {% comment %} <p class="card-text"> {{ blog.blog_content|range_filter|truncatewords:30 }} </p> {% endcomment %}
             <div class="d-flex">
                 <a href="{% url 'Blog:update_category' pk=category.pk %}" class="btn btn-warning btn-sm">Edit</a>
                 <a href="{% url 'Blog:delete_category' pk=category.pk %}" class="btn btn-danger btn-sm ms-2">Delete</a>  
             </div>
          </div>
          <div class="card-footer">
            {% comment %} <small class="text-body-secondary">Last updated: {{ blog.update_date }}</small> {% endcomment %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% comment %} <nav aria-label="Page navigation example ">
      <ul class="pagination justify-content-center">
      

      {% if blogs.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ blogs.previous_page_number }}">Previous</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link">Previous</a>
        </li>
      {% endif %}
  

      {% for blog_page in blogs.paginator.page_range %}
          {% if blogs.number == blog_page %}
         
              <li class="page-item active"><a class="page-link" href="?page={{ blog_page }}">{{ blog_page }}</a></li>
          {% else %}
    
              <li class="page-item"><a class="page-link" href="?page={{ blog_page }}">{{ blog_page }}</a></li>
          {% endif %}
      {% endfor %}
  
      {% if blogs.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ blogs.next_page_number }}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link">Next</a>
        </li>
      {% endif %}
      
      </ul>
  </nav> {% endcomment %}
   
  </div>
</div>
{% else %}
<p>No Post in this category yet.</p>
<a href="{% url 'Blog:create_blog' %}" class="btn btn-primary btn-sm">Add Post</a>
{% endif %}


{% endblock  %}